# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='liked',
            field=models.ManyToManyField(related_name='quotein', to='quoteable.User'),
        ),
    ]
