# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteable', '0002_quote_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='poster',
        ),
    ]
