# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteable', '0003_remove_quote_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.CharField(default='jase', max_length=255),
        ),
    ]
