# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteable', '0004_quote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='liked',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='quoteinlikes', to='quoteable.User'),
        ),
    ]
